teams:
  -
    name: default
    title: Теплая вечеринка со смузи
    password: "40bd001563085fc35165329ea1ff5c5ecbdbbeef"
  -
    name: test
    title: Тестовая вечеринка
    password: "5f6955d227a320c7f1f6c7da2a6d96a851a8118f"
